def gag():
    print('barev')
print ('karmir arev')
print ('karmir arev')
print ('karmir arev')
print ('karmir arev')
print ('karmir arev')
print ('karmir arev')
print ('karmir arev')
print ('karmir arev')
print ('karmir arev')
print ('karmir arev')
print ('karmir arev')
